# Generated by Django 2.2.3 on 2019-07-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kebun_Binatang', '0002_auto_20190722_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hewan',
            name='berat',
            field=models.CharField(max_length=17),
        ),
    ]
