# Generated by Django 2.2.3 on 2019-07-22 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('nomor_telepon', models.PositiveIntegerField()),
                ('jabatan', models.TextField(max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='Mata_Pelajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelajaran', models.CharField(max_length=50)),
                ('jadwal_dimulai', models.DateTimeField()),
                ('jadwal_berakhir', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('nomor_telepon', models.PositiveIntegerField()),
                ('nomor_absen', models.PositiveIntegerField()),
                ('nilai_ratarata', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('nomor_telepon', models.PositiveIntegerField()),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATA.Mata_Pelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='Live_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_live_code', models.CharField(max_length=255)),
                ('banyak_soal', models.PositiveIntegerField()),
                ('bobot_nilai', models.PositiveIntegerField()),
                ('tanggal_pelaksaan', models.DateTimeField()),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATA.Mata_Pelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_challenge', models.CharField(max_length=255)),
                ('banyak_soal', models.PositiveIntegerField()),
                ('bobot_nilai', models.PositiveIntegerField()),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATA.Mata_Pelajaran')),
            ],
        ),
    ]
